### ISSUE TITLE
Auto fill failed again and password show as paint text

### ISSUE THREAD

**Issue by gynet** [perfectapi/CKP#35] opened 2015-05-27 01:43 UTC
Auto fill failed again and password show as paint text. kdbx modified by MacPass.

**Comment by DukeyToo** [comment] 2015-05-27 11:36
I don't have any plans to fix the password displaying as plain text - it is an artifact of KyPass/MacPass.  

For the autofill failing, it was tested for that scenario and worked for me.  Are you running the latest version, 2015.5.19?

**Comment by gynet** [comment] 2015-05-27 14:03
I am running hte latest version  2015.5.19. My db works fine before using this verison, it does not work recently, I just remember I used MacPass to add an entry. Not sure if it cause the problem. Thanks

**Comment by DukeyToo** [comment] 2015-05-28 01:00
I am not able to reproduce this problem.  I created a kdbx file and added an entry with the latest version of MacPass.  I was able to autofill and copy the password successfully.

I need more information in order to fix.  If you could email me a sample database that shows the problem, that would allow me to debug.  steve@perfectapi.com.

Thanks!

**Comment by gynet** [comment] 2015-05-28 01:13
Sent one

Thanks

**Comment by DukeyToo** [comment] 2015-05-28 01:27
Ah, sorry Yue I did not notice this was from you.  I think I screwed up the release 2015.5.19, since I confirmed it is still not fixed there, but works fine on master branch.  I will push a new release with the fix.

**Comment by gynet** [comment] 2015-05-28 01:29
That’s fine.

Thanks,
Yue

**Comment by DukeyToo** [comment] 2015-05-28 02:28
Verified, fixed in release 2015.5.27

**Closed by DukeyToo** 2015-05-28 02:28 UTC
Labels: bug
