### ISSUE TITLE
Autofill and copy password does not work for Chrome in Mac

### ISSUE THREAD

**Issue by gynet** [perfectapi/CKP#33] opened 2015-05-19 03:01 UTC
Autofill and copy does not work for Chrome in Mac, it only fill user name, does not work for password

**Comment by gynet** [comment] 2015-05-19 05:12
It only works for the test database.

**Comment by gynet** [comment] 2015-05-19 05:14
The is no option "Show password" if I select the entry manually, all passwords are shown as paint text

**Comment by gynet** [comment] 2015-05-19 05:15
Using Chrome 42.0.2311.152 (64-bit) for Mac

**Comment by gynet** [comment] 2015-05-19 05:18
CKP is the best solution for Chrome I have seen so far, hope the mac version to be fixed soon.

**Comment by DukeyToo** [comment] 2015-05-19 11:44
The fact that passwords are not hidden for you is strange, and probably why the password autofill does not work - it does not know that it is a password field.  Is this a KDB file?  Is the label of the password field "password", all lowercase?

**Comment by gynet** [comment] 2015-05-19 11:50
It's a kdbx file and lowercase file name. I create a new kdbx file with only one entry， it has the same problem. I think maybe permission issue with mac chrome.

**Comment by DukeyToo** [comment] 2015-05-19 11:50
Thanks for reporting this...I will investigate asap.

**Comment by DukeyToo** [comment] 2015-05-19 11:53
What app did you use to create the KDBX file?

**Comment by gynet** [comment] 2015-05-19 11:54
Kypass

**Comment by gynet** [comment] 2015-05-19 11:57
The first letter of each field is upper case, "Password"

**Comment by gynet** [comment] 2015-05-19 12:01
The sample entry created in the new db still works with the test form.

**Comment by gynet** [comment] 2015-05-19 12:02
not work for any new entry added with other URL domains

**Comment by ciaran-byrne** [comment] 2015-05-19 13:39
I'm using Chrome on a Mac and can try a sample file if its posted

**Comment by gynet** [comment] 2015-05-19 13:54
I just tried on a Windows machine, it previously works fine, but it can not work either now.

**Comment by DukeyToo** [comment] 2015-05-20 00:20
For me, all of my existing test files work fine on Windows and Mac.  The problem is more likely something unusual about how KyPass stores the file, and that is causing an issue for CKP.  

I need a sample file to be able to test a fix for this.  @gynet could you attach a sample file from KyPass?  Be sure to add at least one entry with a password (in addition to whatever samples are in a new blank database from KyPass).  Thanks!

**Comment by gynet** [comment] 2015-05-20 00:31
Aldready sent a kdbx file with facebook entry

**Comment by DukeyToo** [comment] 2015-05-20 00:45
Thanks!  I am able to reproduce with this file and can make a fix to CKP.

The problem is that KyPass is not adding a layer of streaming encryption on the password field, and CKP is expecting that to always be there.   (The password is still encrypted in the main file, it is just that KDBX files normally store passwords with a second layer of protection).

**Closed** 2015-05-20 01:03 UTC
Labels: bug

**Comment by DukeyToo** [comment] 2015-05-20 01:07
Fixed in release 2015.5.19
