### ISSUE TITLE
CKP on ASUS Chromebook C201P Mangles Passwords

### ISSUE THREAD

**Issue by zipsonic** [perfectapi/CKP#142] opened 2016-11-29 05:20 UTC
Keepass v1 database located on Google Drive.

Installed extension from Chrome Web Store. Configured to access from Google Drive. Found Database. Accepted Master Password. CKP gave entry suggestions the same as on a PC. When using the copy feature or the autofill, the extension delivers a garbled password. When clicking the eye icon, then "show", the password shows � "replacement characters", specifically a number of random characters interspersed with black diamonds with question marks.

I have attached a screenshot showing the problem. The password shown is nowhere close to the actual password.

This is a non-Intel (Rockchip) based chromebook, so I wonder if the issue is related to the architecture.

![screenshot 2016-11-28 at 9 18 53 pm](https://cloud.githubusercontent.com/assets/24240628/20697729/562277f8-b5b0-11e6-96b4-8bdabe04638a.png)

**Comment by DukeyToo** [comment] 2016-11-29 12:26
This is a duplicate of #138 introduced by recent changes - it should be fixed as of today.

**Closed** 2016-11-30 00:42 UTC
